"""add_has_password_is_email_verified

Revision ID: ac239175df05
Revises: eb3b51b19ff8
Create Date: 2026-02-18 18:30:49.888354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac239175df05'
down_revision: Union[str, Sequence[str], None] = 'eb3b51b19ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_password', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_password')
    # ### end Alembic commands ###
